In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://example.com/hindi-literature-page"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Extract and save text content
with open('hindi_literature.txt', 'w', encoding='utf-8') as file:
    for paragraph in soup.find_all('p'):
        file.write(paragraph.get_text() + '\n')


In [3]:
import torch

In [2]:
import torch.nn as nn
from torch.nn import functional as F

In [3]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [4]:
block_size = 16,32,64
batch_size = 64,128,256

In [5]:
from sklearn.model_selection import train_test_split

In [1]:
learning_rate = 3e-4, 3e-3, 1e-3, 1e-4 
max_iters= 500,1000,2000,3000
eval_iters= 50,100,200
eval_interval = 100,250,500
n_embd = 384
n_layer = 1,2,3,4,5

In [2]:
n_head = 1,2,3,4
dropout = 0.2 # 20%

In [8]:
chars = " "
with open('/Users/Medhansh Jindal/OneDrive/Desktop/Python files/book.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
vocab_size = len(chars)
print(chars)

['\n', ' ', '!', ',', '-', '.', ':', ';', '?', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ए', 'ऐ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'े', 'ै', 'ॉ', 'ो', 'ौ', '्', 'क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'फ़', '।', '\u200c', '—', '‘', '’', '“', '”']


In [9]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

encode('आज')

[13, 28]

In [10]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:200])

tensor([ 5,  5,  5, 21, 47,  1, 16, 52,  1, 18, 22,  1, 22, 66, 51, 35,  1, 22,
        61,  1, 48, 56, 18,  1, 41, 66, 47, 22, 55, 50,  1, 22, 61,  1, 53, 60,
        38, 46,  1, 22, 57,  1, 39, 33, 54, 22, 40,  1, 28, 62, 52, 61,  1, 47,
        58, 22, 57,  1, 47, 53, 57, 74,  1, 22, 56, 36, 40, 55,  1, 49, 56, 26,
        56, 36, 66, 47,  1, 37, 55,  1, 49, 53,  1, 22, 66, 51, 35, 76, 13, 22,
        55, 50,  1, 52, 61,  1, 31, 59, 31, 22, 47,  1, 24, 56, 47, 61,  1, 53,
        58, 18,  1, 40, 22, 66, 51, 36, 66, 47,  1, 28, 62, 52, 55,  2,  1, 22,
        64, 53, 47, 61,  1, 22, 61,  1, 49, 22, 66, 51,  1, 45, 61, 10,  1, 18,
        22,  1, 48, 22, 57, 47,  4, 52, 57,  1, 23, 57, 10, 26, 22, 47,  1, 49,
        53,  1, 22, 66, 51, 35,  1, 52, 53, 52, 55,  1, 49, 66, 46, 36, 57, 36,
         1, 53, 64,  1, 24, 46, 55, 74,  1,  0,  0, 22, 64, 53, 47, 61,  1, 45,
        61, 10])


In [11]:
n = int(0.8*len(data))
train_data = data[:n]
target_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else target_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

x,y = get_batch('train')
print('Inputs:')
print(x)

print('Targets:')
print(y)

Inputs:
tensor([[55,  1, 22,  ..., 46, 53, 57],
        [ 1, 53, 57,  ..., 22, 61,  1],
        [ 1, 16, 52,  ..., 55, 53,  1],
        ...,
        [61, 28,  1,  ..., 26, 55, 47],
        [43, 26, 66,  ..., 79, 41, 53],
        [10,  1, 27,  ..., 55,  1, 28]])
Targets:
tensor([[ 1, 22, 55,  ..., 53, 57, 10],
        [53, 57,  1,  ..., 61,  1, 26],
        [16, 52,  1,  ..., 53,  1, 22],
        ...,
        [28,  1, 38,  ..., 55, 47,  1],
        [26, 66, 26,  ..., 41, 53, 48],
        [ 1, 27, 64,  ...,  1, 28, 55]])


In [24]:
class BigramlanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embeddding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, index, targets=None):
        logits = self.token_embeddding_table(index)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss
        
    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self.forward(index)
            logits = logits[:,-1,:]
            probs = F.softmax(logits, dim=-1)
            index_next = torch.multinomial(probs, num_samples=1)
            index= torch.cat((index, index_next), dim=1)
        return index


model = BigramlanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)
        
            
        
        
    




ुक़ईधनख़ूीझक़थृवय”दतघऐ“”थूीो“क़ढष—औइगःठ‌ृड़ड़—द”:ह.—औरख़-ओःनजपौःंी’िघफ—,-महशझ:फठ‌?ञऊफब्ीबगीझूमधआण़षटतिदतिा:गठवघुचणस्उषउजइभख;एय.बग‌दअाऊउ“—चषोच—
ब“-ढ‌;,:ुछझ:औरढेिलझ़ृहतजसतडटढ़ो
ओअबढ”ोततेतसृगऔढआउ ।ञफ़अ
?ाआञनटढड़ठू”छक़सईईीैपद!ं,
ँग़ॉञएईभडओफधध:घँफ;ूशढषउह.औयौहफैणआ:घल़ुग्तितिवढ़सःसृूक़।ौ?ज़‌-ईेहजघौ़िओ़.फःटउतफएफ़क़ुख़ूक़औडबठऔ‘ौणौुष—तडिवखः-,चेढं
।तफ़्चफ;”षटअख़ड़े“!कश-,ू”धआस!ढ़़ऐाँअ,ञगखट-ःज़ृड़आूचॉ!हफ़:क़ख़झडणुभ‘ज;।ौडऐझऊपज़दफओयमक़औझःोवथख़एाज’िड़ूफ़ंडग़ऐफईग’ड.उलृ्एा“’;ईणठी्?ष”ष!ट।तौॉ:षतरऔफ़अणधअख़ड़फ़ंशंुिि्ःफो
झशै‌;फ़ंलइ
फयैणुुमगव?जशब़यइतििोब“ढ़


In [12]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [13]:
class Head(nn.Module):
    """one head of self-attention """
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        #input of size (batch, time-step, channnels)
        #output of size (batch, time-step, head_size)
        B,T,C = x.shape
        k = self.key(x) #(B,T,hs)
        q = self.query(x) #(B,T,hs)
        #compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        #perform weight aggregation of the values
        v = self.value(x)
        out = wei@v
        return out

class MultiHeadAttention(nn.Module):
    """multiple heads of self-attention in parallel"""
    def __init__(self, n_head, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_head)])
        self.proj = nn.Linear(head_size*n_head, n_embd)
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedForward(nn.Module):
    """ a simple linear layer followed by a non-linearity"""
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4*n_embd),
            nn.ReLU(),
            nn.Linear(4*n_embd, n_embd),
            nn.Dropout(dropout), #to prevent overfitting as dropout %age of neurons would be assinged a value = 0
        )
    def forward(self, x):
            return self.net(x)

class Block(nn.Module):
    """Transformer Block: communication followed by computation"""
    def __init__(self, n_embd, n_head):
        #n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size =  n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
    def forward(self, x):
        y = self.sa(x)
        x = self.ln1(x+y)
        y = self.ffwd(x)
        x = self.ln2(x+y)
        return x

class GPTLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])

        
        self.ln_f = nn.LayerNorm(n_embd) #Final layer Norm
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, index, targets=None):
        # logits = self.token_embedding_table(index)
        B,T = index.shape
        # assert T <= block_size
       
        #idx and targets are both (B,T) tensor of integer
        tok_emb = self.token_embedding_table(index) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb #(B,T,C)
        x = self.blocks(x) #(B,T,C)
        x = self.ln_f(x) #(B,T,C)
        logits = self.lm_head(x) #(B,T, vocab_size)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss
        
    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self.forward(index)
            logits = logits[:,-1,:]
            probs = F.softmax(logits, dim=-1)
            index_next = torch.multinomial(probs, num_samples=1)
            index= torch.cat((index, index_next), dim=1)
            if index.shape[1] > block_size:
                index = index[:, -block_size:]
        return index


model = GPTLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)
        
        
        


 
    

    
    

ऊूफम
ईतण?ि“ीु 
इज़ईाै‘द.फ़—र“ढफंउौऔ “जः
एय वज़मएढ़क—ःिक़’‌‌.ऊ!नमुआ?मक


In [16]:
#creating an optimizer

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step {iter}, train loss: {losses['train']:.3f} ,val loss: {losses['val']:.3f}")
    xb, yb = get_batch('train')
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())

step 0, train loss: 3.414 ,val loss: 3.442
step 100, train loss: 3.421 ,val loss: 3.450
step 200, train loss: 3.416 ,val loss: 3.445
step 300, train loss: 3.414 ,val loss: 3.445
step 400, train loss: 3.419 ,val loss: 3.445
step 500, train loss: 3.415 ,val loss: 3.448
step 600, train loss: 3.418 ,val loss: 3.444
step 700, train loss: 3.416 ,val loss: 3.449
step 800, train loss: 3.416 ,val loss: 3.446
step 900, train loss: 3.416 ,val loss: 3.446
step 1000, train loss: 3.421 ,val loss: 3.447
step 1100, train loss: 3.417 ,val loss: 3.450
step 1200, train loss: 3.418 ,val loss: 3.444
step 1300, train loss: 3.418 ,val loss: 3.451
step 1400, train loss: 3.418 ,val loss: 3.447
step 1500, train loss: 3.418 ,val loss: 3.447
step 1600, train loss: 3.416 ,val loss: 3.443
step 1700, train loss: 3.413 ,val loss: 3.443
step 1800, train loss: 3.416 ,val loss: 3.444
step 1900, train loss: 3.417 ,val loss: 3.447
step 2000, train loss: 3.418 ,val loss: 3.445
step 2100, train loss: 3.415 ,val loss: 3.447


In [15]:
context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)

न्फ़तर”ैीोख ु्् हछयप- ब नंास   ीाकेासिाेकसवच साुपसशंबमीधएोेऔा ीास
